accounts/urls.py
from django.urls import path
from .forms import UserLoginForm
from .views import (
    SignUpView, 
    PwdResetConfirmView, 
    AccountDetailsView, 
    EditProfileView, 
    GeneralView, 
    UpdatePasswordView,
    PwdResetView,
    AccountLikesView
)
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,   
)

app_name = 'accounts'

urlpatterns = [
    
    path('login', LoginView.as_view(template_name='accounts/login.html', form_class=UserLoginForm, redirect_authenticated_user=True), name='login'),
    path('logout', LogoutView.as_view(next_page="shots:shot_list"), name='logout'),
    path('signup', SignUpView.as_view(), name='signup'),
    path("password", UpdatePasswordView.as_view(), name="password_change"),
    path('password/reset_password', PwdResetView.as_view(), name='password_reset'),
    path('<username>/<pk>', AccountDetailsView.as_view(), name='user_details'),
    path("likes/<username>/<pk>", AccountLikesView.as_view(), name="liked_shots"),
    path('update/<username>/<pk>', EditProfileView.as_view(), name='account_update'),
    path('general/<username>/<pk>', GeneralView.as_view(), name='general_edit'),
    path('password/<uidb64>/<token>', PwdResetConfirmView.as_view(), name='pwd_reset_confirm'),
    
]

actions/urls.py
from django.urls import path
from actions.views import LikeShot, FollowUser, DeleteFeedbackView

app_name="actions"
urlpatterns = [
    path('like/', LikeShot.as_view(), name='like_shot'),
    path('follow/', FollowUser.as_view(), name='follow_user'),
    path('delete/shot', DeleteFeedbackView.as_view(), name='delete_feedback')
]

dribble_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("shots.urls", namespace="shots")),
    path("actions/", include("actions.urls", namespace="actions")),
    
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shots/urls.py
from django.urls import path
from shots.views import ShotListView, CreateShotView, ShotDetailsView, DeleteShotView


app_name = "shots"
urlpatterns = [
    path('', ShotListView.as_view(), name='shot_list'),
    path('uploads/new', CreateShotView.as_view(), name="create_shot"),
    path('<slug:category>/', ShotListView.as_view(), name='shot_list_category'),
    path('details/<uuid:shot_uuid>', ShotDetailsView.as_view(), name="shot_details"),
    path('delete/<uuid:shot_uuid>', DeleteShotView.as_view(), name='delete_shot')
]

shots/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext_lazy as _

from utils.file_upload_helpers import upload_shotcover_hook, upload_shotfiles_hook

class ShotCategory(models.Model):
    title = models.CharField(max_length=80, unique="True", db_index=True)
    slug = models.SlugField(_("Slug"), max_length=80, blank=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.title
    


class ShotFile(models.Model):
    shot = models.ForeignKey("Shot", on_delete=models.CASCADE, related_name="shot_files")
    file = models.FileField(upload_to=upload_shotfiles_hook, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'mp4', 'webp'])])

class Shot(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='shots')
    shot_uuid = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, editable=False)
    category = models.ForeignKey(ShotCategory, related_name="shots", on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=60, blank=True)
    description = models.TextField(help_text=_("Describe your shots"),blank=True)
    cover_shot = models.FileField(upload_to=upload_shotcover_hook, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'mp4', 'webp'])])
    user_like = models.ManyToManyField(get_user_model(), related_name='likes', blank=True)
    view_count = models.PositiveIntegerField(default=0, db_index=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("shots:shot_details", kwargs={"shot_uuid": self.shot_uuid})

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["-created"]

    def save(self, *args, **kwargs):
        original_slug = slugify(self.title)
        queryset =  Shot.objects.all().filter(slug__iexact=original_slug).count()

        count = 1
        slug = original_slug
        while(queryset):
            slug = original_slug + '-' + str(count)
            count += 1
            queryset = Shot.objects.all().filter(slug__iexact=slug).count()

        self.slug = slug
        super(Shot, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ('-created', )

#
@receiver(pre_delete, sender=ShotFile)
def delete_shot_files_hook(sender, instance, using, **kwargs):
    """
        Before deleting ShoFile object, delete the file on disc 
    """
    instance.file.delete()

@receiver(pre_delete, sender=Shot)
def delete_shot_files_hook(sender, instance, using, **kwargs):
    instance.cover_shot.delete()

shots/forms.py
from django import forms
from shots.models import Shot
from django.core.validators import FileExtensionValidator


class ShotForm(forms.ModelForm):
    files  = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'mp4', 'webp'])])
    class Meta:
        model = Shot
        fields = ('title', 'category', 'cover_shot', 'description')

shots/views.py
from typing import Dict, Any

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseServerError, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()
from shots.models import Shot, ShotFile, ShotCategory
from shots.forms import ShotForm
from actions.forms import FeedbackForm
from actions.views import CreateFeedbackView
from actions.models import Feedback



class ShotListView(View):
    template_name = 'shots/shot_list.html'

    def get(self, request, category=None, *args, **kwargs):
        page = request.GET.get("page", 1)
        if category:
            category = get_object_or_404(ShotCategory, slug=category)
            qs = Shot.objects.filter(category=category).order_by('-created')
            shot_qs = qs.select_related('user').prefetch_related('user_like')
        else:
            shot_qs = Shot.objects.select_related("user").prefetch_related('user_like').order_by('-created')

        
        paginator = Paginator(shot_qs, 12)
        try:
            qs = paginator.page(page)
        except PageNotAnInteger:
            qs = paginator.page(1)
        except EmptyPage:
            qs = paginator.page(paginator.num_pages)

            
        context = {
            "shots": qs
        }
        return render(request, self.template_name, context)

class ShotView(SingleObjectMixin, View):
    feedback_qs = Feedback.objects.select_related('user')
    shot_qs = Shot.objects.select_related('user')
    my_queryset = shot_qs.prefetch_related("user_like", "shot_files").prefetch_related(Prefetch('feedbacks', queryset=feedback_qs))
    context_object_name = 'shot'
    template_name = 'shots/shot_detail.html'
    slug_field = 'shot_uuid'
    slug_url_kwarg = 'shot_uuid'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.my_queryset)
        self.object.view_count += 1
        self.object.save(update_fields=['view_count'])
        context = self.get_context_data(object=self.object)
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['feedbackform'] = FeedbackForm

        return context

class ShotDetailsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = ShotView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CreateFeedbackView.as_view()
        return view(request, *args, **kwargs)

class CreateShotView(LoginRequiredMixin, View):
    form_class = ShotForm
    template_name = 'shots/create_shot.html'

    def get(self, request, *args, **kwargs):
        
        return render(request, 'shots/create_shot.html', {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid() and form.is_multipart():
            files = request.FILES.getlist('files')
            cd = form.cleaned_data
            
            shot, created = Shot.objects.get_or_create(user=request.user ,category=cd['category'], title=cd['title'], description=cd['description'], cover_shot=cd['cover_shot'])
            if created:
                
                if len(files) > 0:
                    
                    for file in files:
                        shot_file = ShotFile(shot=shot, file=file)
                        shot_file.save()
                else:
                    pass
            else:
                return HttpResponseServerError()
            messages.success(request, "Shot was created successfully")
            return redirect('shots:shot_details', shot_uuid=shot.shot_uuid)

        else:
            messages.error(request, "Something is missing, please fix below errors")
            return render(request, 'shots/create_shot.html', {'form': form})

class DeleteShotView(LoginRequiredMixin, SingleObjectMixin, View):
    slug_field = 'shot_uuid'
    slug_url_kwarg = 'shot_uuid'
    model = Shot
    success_url = reverse_lazy('shots:shot_list')
    deleted = False
    
    def delete(self, request):
        self.object = self.get_object()     
        if self.object.user == request.user:
            self.object.delete()     
            self.deleted = True
        else:
            self.deleted = False

    def post(self, request, shot_uuid, *args, **kwargs):
        self.delete(request)
        if self.deleted:
            messages.success(request, "Shot was deleted successfully")
            return JsonResponse({"success": True, "url": self.success_url}, status=200)
        else:
            messages.error(request, "Something isn't right")
            messages.warning(request, "You tried deleting someone ele\'s shot, You blocked")
            get_object_or_404(User, username=request.user.username).delete()

            return JsonResponse({"success": False, "url": reverse_lazy("accounts:signup")}, status=500)

shots/templates/shots/create_shot.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Dribble | Upload{% endblock title %}

{% block content %}
    <div class="flex flex-col items-center justify-center space-y-10  mb-16">
        <div class="flex items-center justify-between w-11/12 mx-auto mt-10">
            <div id="reset_form" class="relative py-2 px-3 cursor-pointer text-center rounded-md border-[1px] bg-white flex items-center justify-center space-x-2">
                <p class="text-base font-normal">Cancel</p>
            </div>
            
            <div 
            id="submit_form_btn" 
            class="relative py-2 px-3 text-center cursor-pointer rounded-md text-white border-[1px] bg-[#ea4c89] flex items-center justify-center space-x-2"
            >
                <p class="text-base font-normal">Continue</p>
            </div>
        </div>
        {% if form.errors %}
          <div class="space-y-2">
                {% for field in form %} 
                    {% if field.errors %}
                        <li class="text-sm text-red-500 font-normal">
                        {{field.name}}: {{ field.errors|striptags }}
                        </li>
                    {% endif %} 
                {% endfor %}
            <div>
        {% endif %}
        <form method='post' enctype="multipart/form-data" class="space-y-7">
            
            {% csrf_token %}
            <div>
                <input
                  type="text"
                  name="title"
                  id="id_title"
                  placeholder="Give me a name"
                  class="bg-white h-12 p-3 border-none  outline-none text-2xl font-bold text-[#9199a0]"
                  maxlength="150"
                  required=""
                />
            </div>
            <div class="relative w-[700px] h-[500px] space-y-5">
                <div id="file_holder" class="cursor-pointer relative h-full w-full border-2 border-dotted border-[#e7e7e9] rounded-xl">
                    <div class="file_placeholder flex flex-col items-center justify-center p-4 text-center top-0 left-0 bottom-0 right-0 absolute space-y-5">
                        <img src="{% static 'imgs/placeholde.png' %}" atl="placeholder" class="w-20"/>
                        <div class="text-[#3d3d4e]">
                            Drag and drop an image, or <span class="text-[#ea4c89]">Browser</span>
                       </div>
                       <div class="text-[#6e6d7a] font-normal text-sm">
                           <span>1600x1200 or higher recommended.</span> 
                           <span>Max 10MB each</span> 
                           <span>(20MB for videos)</span>
                        </div>
                        <ul class="flex flex-row flex-wrap max-w-[700px]">
                            <li class="py-1 px-6 w-1/2 text-sm text-left font-normal text-[#6e6d7a]">
                                High resolution images (png, jpg, gif)
                            </li>
                            <li class="py-1 px-6 w-1/2 text-sm text-left font-normal text-[#6e6d7a]">
                                Videos (mp4, 4:3, &lt;60 secs)
                                <span class="p-1 text-center bg-[#ea4c89] text-white rounded-sm text-xs font-medium">
                                    Pro
                                </span>
                            </li>
                            <li class="py-1 px-6 w-1/2 text-sm text-left font-normal text-[#6e6d7a]">
                                Animated gifs (4:3, 800x600 - 1600x1200)
                            </li>
                            <li class="py-1 px-6 w-1/2 text-sm text-left font-normal text-[#6e6d7a]">
                                Only upload media you own the rights to
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <input type="file" name="cover_shot" id="id_cover_shot" accept="image/jpg,image/jpeg,image/pjpeg,image/png,image/apng,image/x-png,image/gif,image/webp" class="w-[0.1px] h-[0.1px] opacity-0 overflow-hidden absolute -z-[1]"> 
            <div id="additional_files_container" class="w-full space-x-4 flex items-center">
                <div id="additional_files" class="cursor-pointer w-full h-28 flex items-center justify-center rounded-md border-2 border-dotted text-center">
                    <p class="text-xl text-[#ea4c89]">Add more files(Max 5 additional files)</p>
                </div>
            </div>
            <input type="file" name="files" size="5" id="id_files" multiple accept="image/jpg,image/jpeg,image/pjpeg,image/png,image/apng,image/x-png,image/gif,image/webp" class="w-[0.1px] h-[0.1px] opacity-0 overflow-hidden absolute -z-[1]"/>
            <div class="grid space-y-42">
                <label for="id_category" class="text-[#9199a0] font-semibold text-base">Shot Category</label>
                <select name="category" required="" id="id_category" class="w-36 h-auto text-sm text-bold border-none outline-none text-[#9199a0]">
                    <option value="" selected="">---------</option>
                    {% for category in categories %}
                        <option value="{{category.id}}">{{category.title}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="w-[700px] max-w-full grid space-y-2 ">
                <label for="id_description" class="text-[#9199a0] font-semibold text-xl">Write what went into this shot, and anything else you'd like to mention</label>
                <textarea type="text" placeholder="ww" name="description" id="id_description" class="resize-y h-32 bg-[#f3f3f4] w-full placeholder:text-xl placeholder:font-bold p-3 border-none focus:outline-none outline-none rounded-md" maxlength="1150">

                </textarea>
            </div>
            <div
                class="text-center h-12 bg-[#ea4c89] w-[150px] rounded-md cursor-pointer"
              >
                <input
                  type="submit"
                  value="Upload shot"
                  class="text-white w-full h-full cursor-pointer text-sm font-semibold"
                />
              </div>
            
        </form>
    </div>
    </div>
{% endblock content %}

{% block javascript %}
<script>
    var form_file = document.querySelector("#file_holder"),
    shot_file = document.querySelector("#id_cover_shot"),
    additional_files = document.querySelector("#additional_files"),
    files = document.querySelector("#id_files"),
    additional_files_container = document.querySelector("#additional_files_container"),
    form = document.querySelector("form"),
    reset_form = document.querySelector("#reset_form")

    reset_form.onclick = (e) => {
        e.preventDefault()
        form.reset()
        window.location.reload(true);
    }

    additional_files.addEventListener("click", () => {
        files.click()
    })

    form_file.addEventListener("click", () => {
        shot_file.click()
        
    })

    files.onchange = ({target}) =>
    {
        if(target.files.length === 0){
            alert("Select atleast 1 file")
        }else{
           if(additional_files)
            {
                additional_files_container.removeChild(additional_files)
                
                for(var i=0; i < target.files.length; i++)
                {
                    console.log(window.URL.createObjectURL(target.files[i]))
                    additional_files_container.innerHTML += `
                        <div id="additional_files" class="cursor-pointer w-28 h-28 flex items-center justify-center rounded-md border-2 border-dotted text-center">
                            <img src="${window.URL.createObjectURL(target.files[i])}" alt="${target.files[i].name}" class="w-full h-full object-cover" />
                        </div>
                    ` 
                }
                
            } 
        }
        
    }

    shot_file.onchange = ({target}) =>
    {
        let file = target.files[0];
        if(file)
        {
            var file_placeholder = document.querySelector(".file_placeholder")
            if(file_placeholder){
                form_file.removeChild(file_placeholder)
                form_file.innerHTML += `
                <img src="${window.URL.createObjectURL(file)}" alt="${file.name}" class="w-full h-full" id="cover_img"/>
            `
            }else{
                document.getElementById('cover_img').src = window.URL.createObjectURL(file)
            }
            
            
        }
    }

</script>
{% endblock javascript %}

shots/templates/shots/shot_list.html
{% extends '_base.html' %}

{% block content %}
<div class="grid items-center justify-center w-11/12 mx-auto space-y-14">
    <div class="flex items-center justify-between">
        <div class="relative py-2 px-3 text-center rounded-md border-[1px] bg-white flex items-center justify-center space-x-2">
            <p class="text-base font-normal">Following</p>
        </div>
        <div class="flex items-center  space-x-5 text-base">
            <a href="/" class="p-2 bg-[#f3f3f4] rounded-md text-center text-[#6e6d7a]">All</a>
            {% for category in categories %}
                <a href="{% url 'shots:shot_list_category' category=category.slug %}" class="p-2" >{{category.title}}</a>
            {% endfor %}
        </div>
        <div class="relative py-2 px-3 text-center rounded-md border-[1px] bg-white flex items-center justify-center space-x-2">
            <p class="text-base font-normal">Filter</p>
        </div>
    </div>
    {% if request.user.is_authenticated and request.user.following.count == 0 %}
        <div class="space-y-3 text-center">
            <h1 class="text-2xl font-bold text-black">You aren't following anyone yet</h1>
            <p><a href="" class="text-[#ea4c89]">Find friend</a> you already know from Twitter.</p>
        </div>
    {% endif %}
    <div class="infinite-container grid items-center grid-cols-[repeat(4,_300px)] grid-rows-[repeat(1,_288px)] gap-8">
        {% for content in shots %}
            <div class="infinite-item  transition-all duration-500 delay-300">
                <div class="relative h-60 w-full rounded-md group transition-all duration-500 delay-300">
                    {% if content.cover_shot.name|slice:"-3:" == 'png' or content.cover_shot.name|slice:"-3:" == 'jpg' or content.cover_shot.name|slice:"-3:" == 'gif' or content.cover_shot.name|slice:"-4:" == 'jpeg' or content.cover_shot.name|slice:"-4:" == 'webp' %}
                        <img class="w-full h-60 rounded-md object-cover" src='{{content.cover_shot.url}}' />
                    {% else %}
                        <video class="responsive-video" autoplay class="w-full h-60 rounded-md object-cover" preload="metadata">
                            <source  src="{{ content.cover_shot.url }}#t=0.5" type="video/mp4">
                        </video>
                    {% endif %}
                    <div class="absolute bottom-0 bg-[#000000bd] transition-all duration-500 delay-300 hidden group-hover:flex rounded-md left-0 h-16 w-full p-4  items-center justify-between">
                        <p class="text-white font-semibold text-lg">
                            <a href="{% url 'shots:shot_details' content.shot_uuid %}">
                                {{content.title}}
                            </a>
                        </p>
                        <div class="flex items-center space-x-3">
                            <p class="w-8 h-8 cursor-pointer rounded-md bg-white text-[#9e9ea7] grid items-center justify-center">
                                <i class='bx bxs-folder-plus text-lg' ></i>
                            </p>
                            {% if request.user.is_authenticated and request.user in content.user_like.all %}
                                <p id="like_btn_{{content.pk}}" 
                                data-action="unlike" 
                                data-uuid={{content.shot_uuid}} 
                                data-id={{content.id}} 
                                onclick="likePost('#like_btn_{{content.pk}}', '.likes-count-{{content.pk}}', '#like-btn-{{content.pk}}')" class="w-8 h-8 cursor-pointer rounded-md bg-white text-[#ea4c89] grid items-center justify-center">
                                    <i class="bx bxs-heart text-lg"></i>
                                </p>
                            {% else %}
                                <p id="like_btn_{{content.pk}}" data-action="like" data-uuid={{content.shot_uuid}} data-id={{content.id}} onclick="likePost('#like_btn_{{content.pk}}', '.likes-count-{{content.pk}}', '#like-btn-{{content.pk}}')" class="w-8 h-8 cursor-pointer rounded-md bg-white text-[#9e9ea7] grid items-center justify-center">
                                    <i class="bx bxs-heart text-lg"></i>
                                </p>
                            {% endif %}
                            
                            
                        </div>
                    </div>
                </div>
                <div class="flex items-center justify-between h-11">
                    <div class="flex items-center space-x-2">
                        {% if content.user.photo %}
                            <div class="h-8 w-8 rounded-full">
                                <img class="w-full h-full rounded-full"src='{{content.user.photo.url}}' />
                            </div>
                        {% else %}
                            <div class="text-center h-8 w-8 rounded-full text-base text-white bg-blue-800"></div>
                        {% endif %}
                        <p class="cursor-pointer">
                            <a class="text-base text-black font-normal" href="{% url "accounts:user_details" content.user.username content.user.pk %}">
                                {{content.user.username}}
                            </a>
                        </p>
                    </div>
                    
                    <div class="flex items-center space-x-2 text-[#9e9ea7] text-lg">
                        {% if request.user.is_authenticated and request.user in content.user_like.all %}
                        <p onclick="likePost('#like-btn-{{content.pk}}', '.likes-count-{{content.pk}}', '#like_btn_{{content.pk}}')" class="group cursor-pointer  text-[#ea4c89]" data-action="unlike" data-uuid={{content.shot_uuid}} data-id={{content.id}} id="like-btn-{{content.pk}}">
                            <i class="bx bxs-heart"></i> 
                            <span id="total-likes" class="text-[#9e9ea7] likes-count-{{content.pk}}">
                                {{content.user_like.count}}
                            </span>
                        </p>
                        {% else %}
                            <p onclick="likePost('#like-btn-{{content.pk}}', '.likes-count-{{content.pk}}', '#like_btn_{{content.pk}}')" class="group cursor-pointer" data-action="like" data-uuid={{content.shot_uuid}} data-id={{content.id}} id="like-btn-{{content.pk}}">
                                <i class="bx bxs-heart group-hover:text-[#ea4c89]"></i> 
                                <span id="total-likes" class="text-[#9e9ea7] likes-count-{{content.pk}}">{{content.user_like.count}}</span>
                            </p>
                        {% endif %}
                        <p  class="group cursor-pointer">
                            <i class='bx bxs-show group-hover:text-[#ea4c89]'></i> 
                            <span>{{content.view_count}}</span>
                        </p>  
                    </div>
                    
                </div>
            </div>
        {% endfor %}

    </div>
    <div class="loading hidden">
        Loading...
    </div>
    <div class="text-center">
        {% if shots.has_next %}
        <div>
            <a class="infinite-more-link" href="?page={{ shots.next_page_number }}">More</a>
        </div>
        {% else %}
        <div>
            <p style="font-size: 1.2rem; ">End of list...</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}


{% block javascript %}
  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').removeClass("hidden");
        $('.loading').addClass("block");
      },
      onAfterPageLoad: function ($items) {
        $('.loading').removeClass("block");
        $('.loading').addClass("hidden");
      }
    });

    //Like Shot
    function likePost(target_id, like_count_id, style_target_id)
    {
        //this.e.preventDefault();
        
        $.ajax({
        type: "POST",
        url: "{% url 'actions:like_shot' %}",
        data: {
            id: $(`${target_id}`).data("id"),
            shot_uuid: $(`${target_id}`).data("uuid"),
            action: $(`${target_id}`).data("action"),
        },
        dataType: "json",

        success: function (data) {
            if (data.success) {
                AjaxRequestsExecuted(target_id, like_count_id, style_target_id)
                }
            else {
                alert("Error occured")
            }
        }
        })
    }

    function AjaxRequestsExecuted(target_id, like_count_id, style_target_id)
    {
        var $prev_action = $(`${target_id}`).data("action");
        var $prev_like = $(`${target_id}`).data("action");
        if(like_count_id){
            var $prev_like_count = $(`${like_count_id}`)
            var $prev_likes = parseInt($prev_like_count.text());
            $prev_like_count.text($prev_action == "like" ? $prev_likes + 1 : $prev_likes - 1)
                   
        }
                
    
        if($prev_action == "like")
        {
            $(`${target_id}`).data("action", "unlike");
            $(`${target_id}`).addClass("text-[#ea4c89]");
            if(style_target_id)
            {
                $(`${style_target_id}`).addClass("text-[#ea4c89]");
            }
                    
        }else {
            $(`${target_id}`).removeClass("text-[#ea4c89]");
            $(`${target_id}`).data("action", "like");
            if(style_target_id)
            {
                $(`${style_target_id}`).removeClass("text-[#ea4c89]");
            }
        }
    }

  </script>
{% endblock javascript %}