accounts/urls.py
from django.urls import path
from .forms import UserLoginForm
from .views import (
    SignUpView, 
    PwdResetConfirmView, 
    AccountDetailsView, 
    EditProfileView, 
    GeneralView, 
    UpdatePasswordView,
    PwdResetView,
    AccountLikesView
)
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,   
)

app_name = 'accounts'

urlpatterns = [
    
    path('login', LoginView.as_view(template_name='accounts/login.html', form_class=UserLoginForm, redirect_authenticated_user=True), name='login'),
    path('logout', LogoutView.as_view(next_page="shots:shot_list"), name='logout'),
    path('signup', SignUpView.as_view(), name='signup'),
    path("password", UpdatePasswordView.as_view(), name="password_change"),
    path('password/reset_password', PwdResetView.as_view(), name='password_reset'),
    path('<username>/<pk>', AccountDetailsView.as_view(), name='user_details'),
    path("likes/<username>/<pk>", AccountLikesView.as_view(), name="liked_shots"),
    path('update/<username>/<pk>', EditProfileView.as_view(), name='account_update'),
    path('general/<username>/<pk>', GeneralView.as_view(), name='general_edit'),
    path('password/<uidb64>/<token>', PwdResetConfirmView.as_view(), name='pwd_reset_confirm'),
    
]

dribble_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("shots.urls", namespace="shots")),
    path("actions/", include("actions.urls", namespace="actions")),
    
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shots/urls.py
from django.urls import path
from shots.views import ShotListView, CreateShotView, ShotDetailsView, DeleteShotView


app_name = "shots"
urlpatterns = [
    path('', ShotListView.as_view(), name='shot_list'),
    path('uploads/new', CreateShotView.as_view(), name="create_shot"),
    path('<slug:category>/', ShotListView.as_view(), name='shot_list_category'),
    path('details/<uuid:shot_uuid>', ShotDetailsView.as_view(), name="shot_details"),
    path('delete/<uuid:shot_uuid>', DeleteShotView.as_view(), name='delete_shot')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.db.models.signals import pre_delete
from django.dispatch import receiver

def handle_profile_upload(instance, filename):
    return f"profile/myimage_{instance.pk}/{filename}"

class CustomUser(AbstractUser):
    photo = models.ImageField(upload_to="profile/", blank=True)
    biography = models.TextField(blank=True)
    location = models.CharField(max_length=150, blank=True)
    website = models.URLField(blank=True, null=True)
    following = models.ManyToManyField('self', through='Contact', symmetrical=False, related_name='followers')


    class Meta:
        verbose_name = "Accounts"
        verbose_name_plural = "Accounts"

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            'driblle@clone.com',
            [self.email],
            fail_silently=False,
        )
    
    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse_lazy("accounts:user_details", kwargs={"username": self.username, 'pk': self.pk})
    
class Contact(models.Model):
    user_from = models.ForeignKey(CustomUser, related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey(CustomUser, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'

# Signals for deleting object file from memory disk
@receiver(pre_delete, sender=CustomUser)
def delete_content_files_hook(sender, instance, using, **kwargs):
	instance.photo.delete()

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm, PasswordResetForm,
                                       SetPasswordForm, UserCreationForm)

User = get_user_model()

class UserLoginForm(AuthenticationForm):

    username = forms.CharField(error_messages={'required': 'Sorry, please enter your username'}, widget=forms.TextInput(
        attrs={'id': 'login__username',
        'placeholder': 'Username'}))
    password = forms.CharField(error_messages={'required': 'Sorry, please enter your password'}, widget=forms.PasswordInput(
        attrs={
            
            'id': 'login__password',
            'placeholder': 'Password'
        }
    ))

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username)
        
        if not user.exists():
            raise forms.ValidationError('This username doesn\'t exist, please provide a valid username')

        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        username = self.cleaned_data['username']
        user = User.objects.get(username=username)
        if user.check_password(password):
            return password

        raise forms.ValidationError('Your password is incorrect')

class RegistrationForm(UserCreationForm):
    """
    Registration Form - create new user using username, email and password
    """

    email = forms.EmailField(required=True)

    class Meta(UserCreationForm):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'first_name')

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError("This email already exists")
        return email

class PwdResetForm(PasswordResetForm):
    """
    Custom password reset form
    """

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'placeholder': 'Email', 'id': 'reset_form_email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Unfortunatley we can not find this email address')
        if not User.objects.get(email=email).is_active:
            raise forms.ValidationError('Unfortunatley, your email address is not verified')

        return email

class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(
            attrs={'placeholder': 'New password', 'id': 'reset_form_newpassword'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(
            attrs={'placeholder': 'Retype-New password', 'id': 'reset_form_newpassword2'}))

class AccountUpdateForm(forms.ModelForm):
        
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'photo', 'biography', 'website', 'location']

class GeneralEditForm(forms.ModelForm):
    """
        Form to edit only username and email
    """
    class Meta:
        model = User
        fields = ["username", "email"]

accounts/views.py
from email import message
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.urls.base import reverse_lazy
from .forms import RegistrationForm, PwdResetConfirmForm, AccountUpdateForm, GeneralEditForm, PwdResetForm
from django.contrib.auth.mixins import LoginRequiredMixin

User = get_user_model()
# Create your views here.
from django.views.generic import View, CreateView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import PasswordChangeForm
from shots.models import Shot

class SignUpView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = RegistrationForm

    def form_invalid(self, form):
        result = super().form_valid(form)
        messages.error(self.request, "Something isn\'t, please fix below errors")
        return result

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        messages.success(self.request, "Account created successfully")
        return result


class AccountDetailsView(DetailView):
    model = User
    slug_field = 'username'
    context_object_name = 'user'
    slug_url_kwarg = 'username'
    query_pk_and_slug = True
    template_name = 'accounts/manage/user_index.html'

class AccountLikesView(View):
    """
        Displays all shots that the user liked. 
    """
    model = User
    template_name = "accounts/manage/account_likes.html"

    def get(self, request, username, pk, *args, **kwargs):
        # filter shots
        try:
            user = self.model.objects.prefetch_related("likes").get(username=username, pk=pk)
            return render(request, self.template_name, {"user": user})
        except self.model.DoesNotExist:
            pass

class EditProfileView(LoginRequiredMixin, View):
    model = None
    form_class = AccountUpdateForm
    template_name = "accounts/manage/edit_profile.html"

    def get_user(self, username, pk):
        user = get_object_or_404(User, username=username, pk=pk)
        return user

    def dispatch(self, request, username, pk, *args, **kwargs):
        self.model = self.get_user(username, pk)
        if request.user != self.model:
            pass
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.model)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            self.model.photo = cd["photo"]
            self.model.location = cd["location"]
            self.model.first_name = cd["first_name"]
            self.model.last_name = cd["last_name"]
            self.model.website = cd["website"]
            self.model.biography = cd["biography"]
            self.model.save(update_fields=["first_name", "last_name", "website", "biography", "location", "photo"])
            messages.success(request, "Account updated successfully")
            return redirect("accounts:account_update", username=self.model.username, pk=self.model.pk)
        else:
            messages.error(request, "Something isn\'t right, please fix below errors")
            return render(request, self.template_name, {"form": form})
    
class GeneralView(LoginRequiredMixin, View):
    model = None
    form_class = GeneralEditForm
    template_name = "accounts/manage/general.html"

    def get_user(self, username, pk):
        user = get_object_or_404(User, username=username, pk=pk)
        return user

    def dispatch(self, request, username, pk, *args, **kwargs):
        self.model = self.get_user(username, pk)
        if request.user != self.model:
            pass
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.model)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            self.model.username = cd["username"]
            self.model.email = cd["email"]
            self.model.save(update_fields=["username", "email"])
            messages.success(request, "Username or email updated successfully")
            return redirect("accounts:general_edit", username=self.model.username, pk=self.model.pk)
        else:
            messages.error(request, "Error receives, please fix all below errors")
            return render(request, self.template_name, {"form": form})

class UpdatePasswordView(LoginRequiredMixin, View):

    form_class = PasswordChangeForm
    template_name = "accounts/password/manage/change_password.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class(request.user)})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated')
            return redirect("accounts:password_change")
        else:
            messages.error(request, 'Error receives, please fix all below errors')
            return render(request, self.template_name, {"form": form})

class PwdResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password/pwd__reset_confirm.html'
    success_url = reverse_lazy('accounts:login')
    form_class=PwdResetConfirmForm

    def form_invalid(self, form):
        messages.error(self.request, "Something isn\'t right, please fix below errors")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Password reset successfully")
        return super().form_valid(form)

class PwdResetView(PasswordResetView):
    template_name='accounts/password/pwd__reset_form.html'
    form_class=PwdResetForm
    success_url=reverse_lazy("accounts:login")
    email_template_name="accounts/password/pwd__reset_email.html"

    def form_invalid(self, form):
        messages.error(self.request, "Something isn\'t right, please fix below errors")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Email sent with password reset instructions")
        return super().form_valid(form)

accounts/templates/accounts/login.html
{% load static %} {% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Sign In | Dribble{% endblock title %}</title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}" />
  </head>
  <body>
    {% if messages %}
            {% for message in messages %}
                <div id="alert" class="cursor-pointer rounded-lg py-5 flex items-center justify-between w-full px-6 text-base bg-blue-100 text-blue-700 mb-3" role="alert">
                    {{message}}
                    <button id="cancel_alert" class="cursor-pointer text-black border-none outline-none text-xl"><i class='bx bx-x'></i></button>
                </div>
            {% endfor %}
        {% endif %}
    <div class="w-full h-screen flex items-center font-sans">
      
      <div class="w-2/5 bg-[#f1cdd7] h-full p-14 space-y-7">
        <h1 class="text-[#a67e8c] text-xl font-semibold">Dribble</h1>

        <p class="text-[#865c6c] text-3xl font-bold">
          Discover the world's top Designers & Creatives.
        </p>
      </div>
      <div class="relative grid items-center justify-center h-full p-6 w-3/5">
        <div class="absolute top-0 right-0 m-7">
          <p>
            Not a member?
            <a href="{% url 'accounts:signup' %}" class="text-blue-400"
              >Sign up</a
            >
          </p>
        </div>
        <div class="space-y-5 w-[400px]">
          <h1 class="text-black text-4xl font-bold">Sign in to Dribbble</h1>
          {% if form.errors %}
          <div class="space-y-2">
            {% for field in form %} {% if field.errors %}
            <li class="text-sm text-red-500 font-normal">
              {{ field.errors|striptags }}
            </li>
            {% endif %} {% endfor %}
          </div>
          {% else %}
          <div class="flex items-center space-x-4">
            <div class="p-3 bg-[#f3f3f4] text-center rounded-md">
              <i class="bx text-lg text-[#6e6d7a] bxl-google"></i>
            </div>
            <div class="p-3 bg-[#f3f3f4] text-center rounded-md">
              <i class="bx text-lg text-[#6e6d7a] bxl-twitter"></i>
            </div>
          </div>
          <div class="flex items-center space-x-2">
            <div class="h-[1.5px] bg-[#f3f3f4] w-full"></div>
            <div class="text-sm text-">Or</div>
            <div class="h-[1.5px] bg-[#f3f3f4] w-full"></div>
          </div>
          {% endif %}
          <div>
            <form method="post" class="space-y-4">
              {% csrf_token %}
              <div class="grid space-y-2">
                <label
                  for="login__username"
                  class="text-black font-semibold text-base"
                  >Username</label
                >
                <input
                  type="text"
                  name="username"
                  id="login__username"
                  class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md"
                  maxlength="150"
                  required=""
                />
              </div>
              <div class="grid space-y-2">
                <div class="flex w-full items-center justify-between text-base">
                  <label
                    for="login__password"
                    class="text-black font-semibold text-base"
                    >Password</label
                  >
                  <a
                    href="{% url 'accounts:password_reset' %}"
                    class="text-blue-700"
                    >Forgot password?</a
                  >
                </div>

                <input
                  type="password"
                  name="password"
                  id="login__password"
                  class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md"
                  required=""
                />
              </div>
              <div
                class="text-center h-12 bg-[#ea4c89] w-[150px] rounded-md cursor-pointer"
              >
                <input
                  type="submit"
                  value="submit"
                  class="text-white w-full h-full cursor-pointer text-sm font-semibold"
                />
              </div>
            </form>
          </div>
          <div></div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script>

      $("#cancel_alert").on("click", function(e){
        e.preventDefault();  
        $("#alert").remove()
      })
    </script>
  </body>
</html>

accounts/templates/accounts/signup.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sign In | Dribble{% endblock title %}</title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div id="alert" class="fixed top-0 left-0 cursor-pointer rounded-lg py-5 flex items-center justify-between w-full px-6 text-base bg-blue-100 text-blue-700 mb-3" role="alert">
                {{message}}
            <button id="cancel_alert" class="cursor-pointer text-black border-none outline-none text-xl"><i class='bx bx-x'></i></button>
            </div>
        {% endfor %}
    {% endif %}
   <div class="w-full h-screen flex items-center font-sans">
       
       <div class="w-2/5 bg-[#f2d184] h-full p-14 space-y-7 fixed left-0 top-0">
           <h1 class="text-[#a67e8c] text-xl font-semibold">Dribble</h1>
            
            <p class="text-[#865c6c] text-3xl font-bold">Discover the world's top Designers & Creatives.</p>
       </div>
       <div class="absolute grid items-center justify-center h-full p-6  w-3/5  right-0 top-0">
            <div class="absolute top-0 right-0 m-7">
                <p>Already a member?  <a href="{% url 'accounts:login' %}" class="text-blue-400">Sign in</a></p>
            </div>
            <div class=" space-y-5 w-[460px]">
                <h1 class="text-black text-4xl font-bold">Sign up to Dribbble</h1>
                {% if form.errors %}
                    <div class="space-y-2">
                        {% for field in form %}
                            {% if field.errors %}<li class="text-sm text-red-500 font-normal">{{ field.errors|striptags }}</li>{% endif %}
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-[#f3f3f4] text-center rounded-md">
                            <i class='bx text-lg text-[#6e6d7a] bxl-google' ></i>
                        </div>
                        <div class="p-3 bg-[#f3f3f4] text-center rounded-md">
                            <i class='bx text-lg text-[#6e6d7a] bxl-twitter'></i>
                        </div>
                    </div>
                    <div class="flex items-center space-x-2">
                        <div class="h-[1.5px] bg-[#f3f3f4] w-full"></div>
                        <div class="text-sm text-">Or</div>
                        <div class="h-[1.5px] bg-[#f3f3f4] w-full"></div>
                    </div>
                {% endif %}
                <div>
                    <form method="post" class="space-y-4">
                        {% csrf_token %}
                        <div class="flex items-center space-x-3">
                            <div class="grid space-y-2 ">
                                <label for="id_first_name" class="text-black font-semibold text-base">Name</label>
                                <input type="text" name="first_name" id="id_first_name" class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md" maxlength="150" required="">
                            </div>
                            <div class="grid space-y-2 ">
                                <label for="id_username" class="text-black font-semibold text-base">Username</label>
                                <input type="text" name="username" maxlength="150" autofocus="" id="id_username" class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md" maxlength="150" required="">
                            </div>
                        </div>
                        <div class="grid space-y-2 ">
                            <label for="login__username" class="text-black font-semibold text-base">Email</label>
                            <input type="email" name="email" id="id_email" class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md" maxlength="150" required="">
                        </div>
                        <div class="flex items-center space-x-3">
                            <div class="grid space-y-2 ">
                                <label for="id_password1" class="text-black font-semibold text-base">Password</label>
                                <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md" minlength="8" maxlength="150" required="">
                            </div>
                            <div class="grid space-y-2 ">
                                <label for="id_password2" class="text-black font-semibold text-base">Re-type password</label>
                                <input type="password" name="password2" id="id_password2" class="bg-[#f3f3f4] h-12 p-3 border-none focus:border-[#f3f3f4] focus:border-[1px] focus:outline-none outline-none rounded-md" minlength="8" maxlength="150" required="">
                            </div>
                        </div>


                        <div class="text-center h-12 bg-[#ea4c89] w-[160px] rounded-md cursor-pointer">
                            <input type="submit" value="Create account" class="text-white w-full h-full cursor-pointer text-sm font-semibold"/>
                        </div>
                        
                    </form>
                </div>
                <div>

                </div>
            </div>
       </div>

   </div>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script>

      $("#cancel_alert").on("click", function(e){
        e.preventDefault();  
        $("#alert").remove()
      })
    </script>
</body>
</html>